language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo 'no installation required'

before_script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

script:
  - docker tag udagram-api-feed orimdominic/udagram-api-feed:v1
  - docker tag udagram-api-user orimdominic/udagram-api-user:v1
  - docker tag udagram-frontend orimdominic/udagram-frontend:v1
  - docker tag udagram-reverseproxy orimdominic/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push orimdominic/udagram-api-feed:v1
  - docker push orimdominic/udagram-api-user:v1
  - docker push orimdominic/udagram-frontend:v1
  - docker push orimdominic/udagram-reverseproxy:v1